# Generated by Django 5.0.3 on 2024-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(),
        ),
    ]
